FS02-62/feature/Screen listado de usuarios
alkemyTech/BBVA-React-T2 pull request #15
Opened 2022-05-11 22:42 UTC by juliascode96

Componente para renderizar página de backoffice con información de los usuarios. El componente incluye una tabla con nombre y email renderizados de la api y botones para editar y borrar usuarios.
![Captura de Pantalla 2022-05-11 a la(s) 19 19 36](https://user-images.githubusercontent.com/92653809/167959217-a6141156-e9ad-4e52-ae93-65203a565208.png)

2022-05-12 01:58 UTC, FlaviaCohen approved these changes

2022-05-12 01:58 UTC, FlaviaCohen commented
Excelente laburo! Nada que corregir, solo falta solucionar conflictos

2022-05-12 16:21 UTC, FlaviaCohen requested changes

2022-05-12 16:21 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    console.log(config)
Ojo que aca hay un console.log, no se si te lo trajiste del main o yo no lo vi pero habria que borrarlo

2022-05-12 17:15 UTC, juliascode96 commented on src/Services/privateApiService.js
> +    console.log(config)
Ya lo borre! Y arreglamos entre todos las url para que queden más uniformes

2022-05-12 23:52 UTC, FlaviaCohen requested changes

2022-05-12 23:52 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    id = id? `/${id}`: '';
Recien lo puse en discord. El servicio get solo recibe endpoint, esta concatenacion se va a hacer directamente en el componente que vaya a utilizar el servicio. Aca ya le llega la url concatenada

2022-05-12 23:52 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +        const url = `${BASE_URL + endpoint + '/' + id}`;
Mismo comentario

2022-05-13 13:18 UTC, juliascode96 commented on src/Services/publicApiService.js
> +        const url = `${BASE_URL + endpoint + '/' + id}`;
Ya nos pusimos de acuerdo con el grupo y arreglamos las url de los métodos en esta rama, asi quedan todos juntos

2022-05-13 14:51 UTC, FlaviaCohen requested changes

2022-05-13 14:51 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +        const url = `${BASE_URL + endpoint}`;
Mismo comentario

2022-05-14 14:16 UTC, FlaviaCohen approved these changes

2022-05-14 14:17 UTC, merged