Feature/fs02 103
alkemyTech/BBVA-React-T2 pull request #16
Opened 2022-05-11 23:38 UTC by Gustavo27Gonzalez

creacion de componente header para web publica, vista mobile y desktop

2022-05-12 01:31 UTC, FlaviaCohen commented
Recorda adjuntar capturas de pantalla en el PR

2022-05-12 01:33 UTC, FlaviaCohen requested changes

2022-05-12 01:33 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +const Login = () => {
Este componente no corresponde a la task 103 (header)

2022-05-12 01:33 UTC, FlaviaCohen commented on src/Components/Login/LoginStyle.css
> +.container-login {
Mismo comentario, es trabajo de otra task

2022-05-12 01:33 UTC, FlaviaCohen commented on src/Components/PublicHeader/PublicHeaderStyles.css
> +    nav{
No es una buena practica referirse directamente a los elementos por su rol, es preferible darles un nombre de clase y llamarlos de esa manera para evitar colisiones de estilo.

2022-05-12 01:33 UTC, FlaviaCohen commented on src/Components/PublicHeader/PublicHeaderStyles.css
> +    ul > li:hover{
Lo mismo para el resto de los elementos

2022-05-12 01:33 UTC, FlaviaCohen commented on src/Services/Login.service.js
> +const setLogin = (body) => {
Esto tampoco corresponde a esta task

2022-05-12 23:20 UTC, FlaviaCohen requested changes

2022-05-12 23:20 UTC, FlaviaCohen commented on src/Components/PublicHeader/PublicHeaderStyles.css
> +@media (min-width: 768px){
Si pones una media query tiene que haber un estilo por default para el resto de las resoluciones. La media query nunca va sola sino que esta asociada a otro estilo.

2022-05-12 23:20 UTC, FlaviaCohen commented
Recorda adjuntar capturas de pantalla al PR

2022-05-13 16:52 UTC, Gustavo27Gonzalez commented
'estilo por default, la media query ya no está sola

2022-05-14 14:05 UTC, FlaviaCohen requested changes

2022-05-14 14:05 UTC, FlaviaCohen commented on src/Components/PublicHeader/PublicHeaderStyles.css
> +  .navbar-container input[type="checkbox"],
Hay que darle una clase a todos los elementos a los que se esta refiriendo por rol. Sino va a llevar a colision de estilos

2022-05-14 14:05 UTC, FlaviaCohen commented on src/Components/PublicHeader/PublicHeaderStyles.css
> +  .navbar-container input[type="checkbox"],
Y porfa adjunta capturas de pantalla al PR

2022-05-16 01:37 UTC, Gustavo27Gonzalez commented
![CapturaHeaderPublicoDesktop](https://user-images.githubusercontent.com/74928839/168505413-e205679f-f966-457f-b323-28577fcdfe27.PNG)
![CapturaHeaderPublicoMobile](https://user-images.githubusercontent.com/74928839/168505418-2ec27318-7863-476f-a424-aeadd3b8ff98.PNG)
![CapturaHeaderPublicoMobileHamburguerMenu](https://user-images.githubusercontent.com/74928839/168505421-6f1fb8de-2913-4f5c-9b42-46b3ab4b31ac.PNG)
Clase asignada a todos los elementos para darles estilos

2022-05-16 14:52 UTC, FlaviaCohen approved these changes

2022-05-16 14:53 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 17:34 UTC, Gustavo27Gonzalez commented
Conflicto solucionado

2022-05-16 23:04 UTC, FlaviaCohen requested changes

2022-05-16 23:04 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +const screenDashboard = () => {
Este componente no corresponde a esta tarea me parece.

2022-05-16 23:04 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +const Put = (endpoint) => {
Y este servicio tampoco, se te mezclaron las branch

2022-05-16 23:32 UTC, Gustavo27Gonzalez commented on src/Services/privateApiService.js
> +const Put = (endpoint) => {
'quite screenDashboard que no corresponde a esta rama y modifique privateApiService dejandolo igual al privateApiService que está actualmente en el repo, ya que agregar el metodo put pertenece a otra rama

2022-05-16 23:37 UTC, FlaviaCohen approved these changes

2022-05-16 23:38 UTC, merged