variables de entorno del endpoint de testimonials agregado
alkemyTech/BBVA-React-T2 pull request #20
Opened 2022-05-12 17:34 UTC by iarabaya

endpoint de testimonials al .env agregado

2022-05-12 23:39 UTC, FlaviaCohen requested changes

2022-05-12 23:39 UTC, FlaviaCohen commented on .env
> +REACT_APP_BASE_URL=https://ongapi.alkemy.org/api/
No es correcto que esta ruta tenga una barrita al final, hay que sacarsela y agregarsela al principio en las otras variables

2022-05-13 00:05 UTC, iarabaya commented on .env
> +REACT_APP_BASE_URL=https://ongapi.alkemy.org/api/
perfecto, gracias, ahi lo modifique junto con la variable de entorno

2022-05-13 14:41 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-13 18:51 UTC, FlaviaCohen approved these changes

2022-05-13 18:51 UTC, merged