FS02-65/feature/variable de entorno 'activities'
alkemyTech/BBVA-React-T2 pull request #23
Opened 2022-05-12 17:56 UTC by variniaquisbert

Acciones que se realizaron en esta rama:

- Agregar en el archivo .env la variable de entorno '_REACT_APP_ACTIVITIES_' con el objetivo de luego utilizarla para almacenar los endpoints de listado, creación, edición y eliminación de Actividades.

pd: borré la otra rama y el pull request porque me dí cuenta que no había creado la rama desde el main, está es la definitiva.

2022-05-12 23:35 UTC, FlaviaCohen requested changes

2022-05-12 23:35 UTC, FlaviaCohen commented on .env
> +REACT_APP_ACTIVITIES=activities
Le falta la barrita

2022-05-13 02:16 UTC, variniaquisbert commented on .env
> +REACT_APP_ACTIVITIES=activities
Es porque habiamos acordado con mi team sacarle la barrita a las variables y ponerse a la _baseUrl_, pero según tengo entendido, un compañero ya corrigió todas las variables para que quedaran con la barrita. Cualquier cosa, avisame

2022-05-13 02:19 UTC, variniaquisbert commented on .env
> +REACT_APP_ACTIVITIES=activities
Pero de todas maneras, hago un commit con eso para que quede resuelto si es necesario.

2022-05-13 14:36 UTC, FlaviaCohen requested changes

2022-05-13 14:36 UTC, FlaviaCohen commented on .env
> +REACT_APP_ACTIVITIES=activities
Le falta la barrita a activities

2022-05-13 14:36 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-13 15:44 UTC, variniaquisbert commented on .env
> +REACT_APP_ACTIVITIES=activities
Ahí lo cambié, disculpa.

2022-05-13 15:46 UTC, variniaquisbert commented
Conflictos solucionados, merge pendiente.

2022-05-14 14:15 UTC, FlaviaCohen approved these changes

2022-05-14 14:15 UTC, merged