Feature/fs02 28
alkemyTech/BBVA-React-T2 pull request #24
Opened 2022-05-12 18:24 UTC by Gustavo27Gonzalez

'Feature/fs02 28 - peticion put para acceder a endpoints privados de la api'

2022-05-12 23:29 UTC, FlaviaCohen requested changes

2022-05-12 23:29 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +const Get = (endpoint, id) => {
Este get no corresponde a esta tarjeta

2022-05-12 23:29 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +const Delete = (endpoint, id) => {
Y este delete tampoco

2022-05-12 23:29 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    axios.put(`${BASE_URL+endpoint+id}`, body, headers)
Recien lo puse en el chat de discord, esta concatenacion se debe hacer en el componente que vaya a utilizar este metodo. Aca solo le llega el endpoint

2022-05-14 14:11 UTC, FlaviaCohen requested changes

2022-05-14 14:11 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    axios.Put(`${endpoint+id}`, headers)
No concatenamos nada en el servicio. La concatenacion se hace directamente en el componente que se vaya a utilizar. Aca no le llega id, solamente enpoint

2022-05-14 14:11 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 01:44 UTC, Gustavo27Gonzalez commented
Ya no se recibe id ni se concatena en método put de services

2022-05-16 14:57 UTC, FlaviaCohen approved these changes

2022-05-16 17:21 UTC, Gustavo27Gonzalez commented
![CapturaSolucionandoMergeConflictMetodoPrivadoPut](https://user-images.githubusercontent.com/74928839/168648329-4eafbedc-62da-44b7-a462-306621e62196.PNG)
Estuve tratando de resolver el conflicto, así creo que ya no debería salir

2022-05-16 17:33 UTC, Gustavo27Gonzalez commented
Conflicto aparentemente solucionado

2022-05-16 23:11 UTC, FlaviaCohen requested changes

2022-05-16 23:11 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +const screenDashboard = () => {
Este componente no corresponde a esta tarjeta, se te estan mezclando las branch Gus. 
Acordate siempre de crear tus branchs a partir de main

2022-05-16 23:11 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboardStyles.css
> +.container-dashboard {
Lo mismo con esto

2022-05-16 23:27 UTC, Gustavo27Gonzalez commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +const screenDashboard = () => {
Acabo de quitar el screenDashboard de esta rama, ya que no está aprobado todavía

2022-05-16 23:40 UTC, FlaviaCohen approved these changes

2022-05-16 23:41 UTC, merged