Feature/fs02-45/componente organization creado y obtencionn del futuro componente edicion del formulario
alkemyTech/BBVA-React-T2 pull request #25
Opened 2022-05-12 21:05 UTC by fede16798

Componente organization creado. Este mismo también viaja a la ruta backoffice/organization/edit y se mostraría el formulario de edición cuando sea creado.

Tengo dos consultas respceto a esto. Una es cuando se muestra el formulario, también se deben mantener la estructura del componente anterior (en este caso organization) y si yo debería crear el HTML formulario (esto último entiendo que no porque la tarjeta no lo dice)

Actualmente el componente organization lo que hace es mostrar los datos de la ONG y si clickea en el botón editar se agregaría al componente el formulario de edición, pero este componente sigue mostrando los datos mencionados anteriormente.

![organization](https://user-images.githubusercontent.com/50428678/168167737-3fdefee0-ed7b-4e96-bfc8-8b841be4dc69.png)

UNA VEZ QU ESE DA CLICK EN EDITAR, SE MOSTRARÍA EL FORMULARIO

![formluario edicion](https://user-images.githubusercontent.com/50428678/168167733-0b3bd5a5-0be6-4420-973b-6fb6699187fc.png)

2022-05-12 21:07 UTC, fede16798 commented
Respecto a crear el formulario, me acabo de dar cuenta que yo tengo esa tarjeta. Pero sigo teniendo la pregunta de si tiene que recargar todo el componente o solo agregarlo al mismo.

2022-05-12 23:44 UTC, FlaviaCohen commented
No esta mal hacerlo asi, yo mostraria solo el formulario si clickeo en editar y al clickear en submit volveria a la vista de datos de organizacion, pero esta bien si lo hiciste asi.

2022-05-12 23:46 UTC, FlaviaCohen requested changes

2022-05-12 23:46 UTC, FlaviaCohen commented on src/App.js
> +          <Route path="/backoffice/organization/edit" component={Organization} />
No es necesario que la ruta tenga el /edit. Se supone que el backoffice es para editar el contenido de la pagina y si estamos entrando a /backoffice/organization esta implicito que es para editar su contenido

2022-05-12 23:46 UTC, FlaviaCohen commented on src/Components/Organization/Organization.js
> +        console.log(showEditForm);
No dejamos console.logs en los PRs

2022-05-13 01:00 UTC, fede16798 commented
Segui tu consejo y ahora aparece uno o el otro. 
También eliminé el 'edit' de la ruta dentro de app. Me surgió la duda si también debería eliminarlo de la ruta del navegador. En la tarejta dice lo siguiente: la acción para acceder al formulario de edición (/backoffice/organization/edit) .
Es por eso que había agregado el /edit. También debería borrarlo del navegador, o en está bien que quede así?

![formulario edicion](https://user-images.githubusercontent.com/50428678/168190318-06e7645a-4d45-4961-873d-2f8ad169e7dc.png)
![datos org](https://user-images.githubusercontent.com/50428678/168190316-061e5d2d-29dd-4b5f-b099-9aa986f91da0.png)

2022-05-13 14:43 UTC, FlaviaCohen requested changes

2022-05-13 14:43 UTC, FlaviaCohen commented on src/Components/Organization/Organization.js
> +    function handleClick (e) {
utilicemos arrow functions para que el codigo quede homogeneo

2022-05-16 16:46 UTC, closed without merging