Feature/fs02 27
alkemyTech/BBVA-React-T2 pull request #29
Opened 2022-05-13 02:39 UTC by variniaquisbert

Acciones realizadas en esta rama:
- Se trabajó sobre el archivo _privateApiServices.js_ eliminando el método _getAuthorization_ y añadiendo el método _POST_ solitado en el ticket.

**Aclaraciones**:
Sólo hice 2 commits ("_remove getAuthorization method_" y "_modified POST method_"). No estoy segura de porqué me traen todos los anteriores commits pero seguro que está mal. Me parece que es porque al hacer el pull me los trae.

2022-05-13 14:32 UTC, FlaviaCohen requested changes

2022-05-13 15:33 UTC, variniaquisbert commented on src/Services/privateApiService.js
> +    const url = `${BASE_URL + endpoint}`;
Perfecto! Gracias por la correción, ahí subí mis cambios. Espero haber entendido a lo que te referias.

2022-05-14 14:09 UTC, FlaviaCohen requested changes

2022-05-14 14:09 UTC, FlaviaCohen commented on src/App.js
> +      <div className="App"></div>
Este div hay que borrarlo. Quedo del template de react

2022-05-14 14:09 UTC, FlaviaCohen commented on src/Components/Header/Header.js
> +        ((!isMenuIconClicked) ? setIsMenuIconClicked(true) : setIsMenuIconClicked(false))
Te simplifico un poco esto: 

```
const handleClick = () => {
    setIsMenuIconClicked(!isMenuIconClicked)
}
```

Y ojo con los nombres de variables demasiado largos. Seria mejor llamarlo isClicked o isOpen

2022-05-14 14:09 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    const url = `${BASE_URL}${endpoint}${id ? `/${id}` : ''}`
Se que esto no te corresponde pero hay que corregirlo. Al servicio le tiene que llegar solo endpoint y trabajar con eso, no hacer ninguna concatenacion. La concatenacion se hará desde el componente. Asi que habria que borrar esta constante url y al axios pasarle solo endpoint

2022-05-14 14:09 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +    axios.delete(`${BASE_URL}/${endpoint}/${id}`, headers)
Lo mismo aca

2022-05-14 14:09 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +        axios.post(endpoint, body)
Este esta perfecto, hay uqe dejar los otros igual

2022-05-14 14:10 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-15 16:52 UTC, variniaquisbert commented on src/App.js
> +      <div className="App"></div>
Solucionado.

2022-05-15 16:52 UTC, variniaquisbert commented on src/Services/privateApiService.js
> +    const url = `${BASE_URL}${endpoint}${id ? `/${id}` : ''}`
No hay problema, ya lo corregí.

2022-05-15 16:52 UTC, variniaquisbert commented on src/Services/privateApiService.js
> +    axios.delete(`${BASE_URL}/${endpoint}/${id}`, headers)
Solucionado.

2022-05-15 16:56 UTC, variniaquisbert commented on src/Components/Header/Header.js
> +        ((!isMenuIconClicked) ? setIsMenuIconClicked(true) : setIsMenuIconClicked(false))
La corrección ya se realizó en la rama correspondiente

2022-05-15 16:57 UTC, variniaquisbert commented
Conflictos solucionados.

2022-05-15 19:18 UTC, FlaviaCohen requested changes

2022-05-15 19:18 UTC, FlaviaCohen commented on src/Components/Header/Header.js
> +        ((!isMenuIconClicked) ? setIsMenuIconClicked(true) : setIsMenuIconClicked(false))
En que rama lo hiciste? porque si mergeo esto va a sobreescribir lo que este corregido. O hiciste un fix?

2022-05-15 19:42 UTC, variniaquisbert commented on src/Components/Header/Header.js
> +        ((!isMenuIconClicked) ? setIsMenuIconClicked(true) : setIsMenuIconClicked(false))
No sé porque se muestra así cuando ya actualicé la rama. Igual ahi lo edité para que quedará como debería. Mandé un commit con el update.

2022-05-15 19:45 UTC, variniaquisbert commented on src/Components/Header/Header.js
> +        ((!isMenuIconClicked) ? setIsMenuIconClicked(true) : setIsMenuIconClicked(false))
![image](https://user-images.githubusercontent.com/105218447/168491141-6d12f084-12bc-46fd-8979-e0d8c605702c.png)

2022-05-16 14:56 UTC, FlaviaCohen approved these changes

2022-05-16 14:56 UTC, merged