FS02-31/feature/metodo post
alkemyTech/BBVA-React-T2 pull request #3
Opened 2022-05-10 13:53 UTC by juliascode96

Creación de un método post genérico en el archivo publicApiService.js que pueda ser reutilizado.

2022-05-10 14:05 UTC, FlaviaCohen requested changes

2022-05-10 14:10 UTC, juliascode96 commented on src/Services/publicApiService.js
>      .catch(err => console.log(err))
Perfecto! En seguida lo hago

2022-05-10 16:17 UTC, FlaviaCohen requested changes

2022-05-10 16:17 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +        return(res)
las arrow functions tienen un return implícito. Podes escribirlo asi para ahorrar código: 

`.then(res => res )`
Lo mismo con el catch

2022-05-10 16:18 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-10 16:24 UTC, juliascode96 commented on src/Services/publicApiService.js
> +        return(res)
Listo!

2022-05-11 02:31 UTC, FlaviaCohen requested changes

2022-05-11 02:31 UTC, FlaviaCohen commented on src/Services/publicApiService.js
> +<<<<<<< HEAD
Aca hay un conflicto sin resolver. Recorda que no es solamente hacer pull del main sino que una vez hecho el pull hay que resolver los conflictos mediante aceptar los "current changes", los "incoming changes" o "both changes". 

Fijate que en el canal de texto de discord de buenas practicas les deje una guia de como resolverlos. Si tenes dudas lo vemos mañana en la daily

2022-05-11 13:04 UTC, juliascode96 commented on src/Services/publicApiService.js
> +<<<<<<< HEAD
Creo que ahí los resolví, cómo puedo ver si queda algún conflicto? VSC ya no me marca ninguno y me dejó hacer full de main sin problema

2022-05-11 13:38 UTC, FlaviaCohen approved these changes

2022-05-11 13:38 UTC, merged