Feature/fs02 48
alkemyTech/BBVA-React-T2 pull request #32
Opened 2022-05-13 18:52 UTC by Gustavo27Gonzalez

![CapturaScreenDashboardBackoffice](https://user-images.githubusercontent.com/74928839/168351450-6dfa3831-a440-4e88-bf02-973cb5bfade7.PNG)
Creado componente screenDashboard para backoffice

2022-05-14 14:20 UTC, FlaviaCohen requested changes

2022-05-14 14:20 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +        <div className="card">
Seria una mejor practica que te crees un componente Card y lo mapees segun un mock. Quedaria mas corto el codigo y no repetirias siempre lo mismo.

2022-05-14 14:20 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboardStyles.css
> +  .name-card > p {
A este elemento hay que darle una clase para evitar colision de estilos

2022-05-16 20:26 UTC, Gustavo27Gonzalez commented
![CapturaScreenDashboard](https://user-images.githubusercontent.com/74928839/168676678-bb660132-8b23-49fa-9a40-117558a2f1ef.PNG)
![CapturaScreenDashboardMobile](https://user-images.githubusercontent.com/74928839/168676685-b78ddd50-0912-4b39-acb9-d150c5e80c6b.PNG)
Creado componente card y mapeado en screendashboard

2022-05-16 23:14 UTC, FlaviaCohen requested changes

2022-05-16 23:14 UTC, FlaviaCohen commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +  const [sectionData, setSectionData] = useState([
esto no tiene que ser un estado, puede ser una constante pero el setSectionData no lo usas para nada. Es decir... es informacion estatica, podes declararla directamente en una constante sin necesidad del useState

2022-05-16 23:38 UTC, Gustavo27Gonzalez commented on src/Components/ScreenDashboard/ScreenDashboard.js
> +  const [sectionData, setSectionData] = useState([
Modifiqué el useState y dejé una constante

2022-05-16 23:44 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-17 00:47 UTC, Gustavo27Gonzalez commented
Estuve solucionando conflictos y comitee de nuevo

2022-05-17 01:42 UTC, FlaviaCohen commented
Todavia hay conflictos. Puede ser porque estuve mergeando PRs eh, no significa que estes haciendo algo mal

2022-05-17 01:54 UTC, Gustavo27Gonzalez commented
Me aparece 'nothing to commit, working tree clean' en esta rama

2022-05-17 13:24 UTC, Gustavo27Gonzalez commented
No me aparece ningún conflicto en la terminal cuando hago pull ni cuando hago push

2022-05-17 15:24 UTC, FlaviaCohen commented
Fijate de estar en la branch correcta, y estar pusheando a la branch correcta. Tiene que llamarse Feature/FS02-48

2022-05-17 15:35 UTC, Gustavo27Gonzalez commented
![CapturaFeature-FS02-48](https://user-images.githubusercontent.com/74928839/168850946-f61dd8cf-953c-45bf-aad8-94d22e5fbd5e.PNG)

2022-05-19 21:53 UTC, closed without merging