Feature/fs02 41/creacion de formulario de organizacion
alkemyTech/BBVA-React-T2 pull request #34
Opened 2022-05-13 22:38 UTC by fede16798

Creado el componente formOrganization. 
Este mismo permite llenar un formluario que posteriormente va a ser enviado a la api.
hace todas las validaciones correspondientes. Que los campos no estén vacíos, que las url sean válidas y que la imagen sea png o jpg.
Intenté (subir un video pero no pude por el tamaño)

![completar todos los campos](https://user-images.githubusercontent.com/50428678/168397734-184ecba0-c770-408f-81e0-be098ec8108a.png)
![url no validas](https://user-images.githubusercontent.com/50428678/168397737-71352b23-270a-4427-9fce-58c00a170b0d.png)
![formato imagen invalido](https://user-images.githubusercontent.com/50428678/168397738-0692eb47-7ae3-4446-8377-e6260444de14.png)
![formulario valido](https://user-images.githubusercontent.com/50428678/168397741-8b9006a3-dae2-449c-bbc3-4b993bb26335.png)

2022-05-14 14:34 UTC, FlaviaCohen requested changes

2022-05-14 14:34 UTC, FlaviaCohen commented on src/Components/Backoffice/Organization/OrganizationForm.js
> +        //comparo cada atributo con el input donde se está escribiendo para actualizarlo
esta logica puede reemplazarse por algo mas simple: 

```
const handleChange = (e) => {
    setInitialValues({...initialValues, [e.target.name]: e.target.value})
}
```

2022-05-14 14:34 UTC, FlaviaCohen commented on src/Components/Backoffice/Organization/OrganizationForm.js
> +    const isBlank = (str) => {
Tenes 3 funciones para validar que los campos no esten vacios, es un poco mucho. 

Te sugiero otro aproach. Te generas un estado `[errors, setErrors] = useState({ aca vas a tener una key por cada input que queiras validar})`

En el handleSubmit vas a verificar que initialValues tenga un valor en cada una de sus keys, si no lo tiene vas a setear un error en tu estado errors, y si algun error existe vas a mostrar un error que diga "tal campo es obligatorio"

2022-05-14 14:34 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-15 20:27 UTC, fede16798 commented on src/Components/Backoffice/Organization/OrganizationForm.js
> +    const isBlank = (str) => {
Intenté hacerlo, no se si lo que hice es lo que me pedías, pero entendí que era algo asi

2022-05-16 15:02 UTC, FlaviaCohen approved these changes

2022-05-16 15:03 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 23:21 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-17 02:47 UTC, FlaviaCohen approved these changes

2022-05-17 02:47 UTC, merged