FS02-52/feature/ Sección Contacto
alkemyTech/BBVA-React-T2 pull request #36
Opened 2022-05-16 13:39 UTC by iarabaya

Creacion del componente Contacto con su respectiva ruta /contact.
Recibe por props los datos de contacto de la ong, sino tiene un valor por defecto a modo de placeholder.
Contiene el Formulario de Contacto (era otro ticket pero cuanto me di cuenta ya lo tenía hecho, igualmente le faltan validaciones pero los estilos ya están)
Screen en pantalla monitor
![contact-screen](https://user-images.githubusercontent.com/48898003/168603565-7edba82e-e92f-4410-b9f3-472bc640d873.PNG)
En pantalla de dispositivo movil (ej Iphone SE)
![contacto-screen](https://user-images.githubusercontent.com/48898003/168605409-921d969c-7bc1-4c2f-aec2-d3adad32103a.gif)

2022-05-16 15:00 UTC, FlaviaCohen requested changes

2022-05-16 15:00 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 17:05 UTC, iarabaya commented on src/Components/Frontoffice/Contact/ContactForm.js
> +    console.log(url)
Listo eliminado el console.log, se me pasó sin querer.
Como el formulario era otro ticket deje varios comentarios para quien tenga que completarlo o reemplazarlo, espero no sea un problema, lo mas seguro es que luego los borren y agreguen toda la logica que le falta

2022-05-16 23:16 UTC, FlaviaCohen commented on src/Components/Frontoffice/Contact/ContactForm.js
> +    console.log(url)
Esta perfecto, es una buena practica dejar comentarios si queda trabajo pendiente

2022-05-16 23:16 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-17 14:08 UTC, iarabaya commented
Buen dia flavia, tuve que agregar varios cambios a ultimo momento porque la app no renderizaba correctamente (aparecian duplicados unos headers) y era un tema de Layouts, asi que ahi esta reestructurado y quedo asi. Tambien hice un pequeño fix a los metodos get de los componentes users y members publicos agregandoles el / que faltaba al url
![final](https://user-images.githubusercontent.com/48898003/168830612-5e665032-e1c5-463c-b2a6-cd50e92dc840.gif)

2022-05-17 15:22 UTC, merged