FS02-40/feature/formulario creación y edición de usuarios
alkemyTech/BBVA-React-T2 pull request #37
Opened 2022-05-16 16:10 UTC by juliascode96

Formulario que permite editar o crear un nuevo usuario dependiendo de si recibe un id por la url o no. El formulario valida que el formato del email sea válido, que el nombre tenga mas de 4 caracteres y que la contraseña tenga mas de 8.
Se excluyo del formulario el campo imagen por problemas de la API.
Se utiliza una llamada a arios para el método put ya que el método reutilizable aun no esta mergeado.
![Captura de Pantalla 2022-05-12 a la(s) 20 50 59](https://user-images.githubusercontent.com/92653809/168636861-86639dfa-46cb-4672-99d2-cae0e36b02b6.png)
![Captura de Pantalla 2022-05-12 a la(s) 20 51 57](https://user-images.githubusercontent.com/92653809/168636865-abd857c0-03d5-42b2-9fe8-cf9552b7ad81.png)
![Captura de Pantalla 2022-05-12 a la(s) 20 51 30](https://user-images.githubusercontent.com/92653809/168636876-d4348acd-0f1e-4c0d-8579-65172af2488e.png)

2022-05-16 16:24 UTC, FlaviaCohen requested changes

2022-05-16 16:24 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +    const validateName = (name) => {
Estas validaciones podes hacerlas todas en la misma funcion. Pasale un parametro input que sea un string ('name' o 'email' o el input que quieras validar) y que dependiendo de cual sea se meta en cada condicional. 

Por ejemplo: 

```
const validate = (input) => {
    if(input == 'name' && input.length < 4) {
        setError('El nombre es demasiado corto')
    }
}
```
Y en la misma funcion metes las otras validaciones

2022-05-16 17:32 UTC, juliascode96 commented on src/Components/Backoffice/Users/UsersForm.js
> +        if(id){
Listo!

2022-05-16 17:55 UTC, juliascode96 commented on src/Components/Backoffice/Users/UsersForm.js
> +    const validateName = (name) => {
Creo que ya corregí todo

2022-05-16 23:35 UTC, FlaviaCohen requested changes

2022-05-16 23:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +                name:res.data.data.name,
Acá para no repetir tanto res.data.data podes desestructurar.
Te quedaria asi: 
```
const {name, email, role_id} = res.data.data

setInitialValues({name, email, roleId, password: ''})
```

Cuando tenes un objeto en el que la key se llama igual que el value podes omitir el value.

2022-05-16 23:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +                    catch(err){}
Aca tendrias que setear el mensaje de error en caso de que exista

2022-05-16 23:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +                    catch(err){}
Lo mismo aca

2022-05-16 23:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +        if(input == initialValues.name && input.length < 4 || input===null) {
Ok... ya entendi lo que queres hacer. 
La forma correcta seria esta: 

```
if(initialValues.name.length < 4 || !initialValues.name){
    ...
} 
if(initialValues.email.match(re) || !initialValues.email){
   ...
}
```
Asi con todos

2022-05-16 23:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +        return validate(initialValues.name) &&
De la forma en la que te comente no vas a necesitar ejecutar estas funciones dentro de validateAll, ejecutas solamente una funcion donde quieras validar y listo

2022-05-16 23:36 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-17 15:35 UTC, FlaviaCohen requested changes

2022-05-17 15:35 UTC, FlaviaCohen commented on src/Components/Backoffice/Users/UsersForm.js
> +    const createUser = async () => {
Te hago una correccion mas. 
En vez de declarar este createUser y editUser que hacen exactamente lo mismo pero con diferentes servicios te propongo lo siguiente: 

```
const handleSubmit = () => {
     e.preventDefault();
     const body = {
            name: initialValues.name.toString(),
            email: initialValues.email.toString(),
            password: initialValues.password.toString(),
            roleId: initialValues.roleId.toString(),
        }
        
         if(validate()) {
                if(id) {
                    try{
                        axios.put(endpoint + '/' + id, body)
                        setError('')
                    } 
                    catch(err){
                        setError(err)
                    }
                else{
                      try{
                        Post(endpoint, body)
                        setError('')
                    } 
                    catch(err){
                        setError(err)
                    }
                }
}
```

Si lo haces asi ya no necesitas las funciones editUser y createUser que hacen practicamente lo mismo

2022-05-17 15:49 UTC, FlaviaCohen approved these changes

2022-05-17 15:49 UTC, FlaviaCohen commented
Falta solucionar conflictos!

2022-05-17 16:09 UTC, FlaviaCohen commented on src/Components/Frontoffice/About/About.js
> +      <div className="title-box"><h1 className="about-title">Nuestros miembros</h1></div>
Este div con el h1 en main no estaba, y no es parte de tu task asi que me parece que hay que borrarlo como estaba en main

2022-05-17 16:24 UTC, merged