FS02-37/feature/formulario de creación y edición de slides
alkemyTech/BBVA-React-T2 pull request #38
Opened 2022-05-16 20:15 UTC by juliascode96

Formulario que permite editar o crear una nueva slide. Contiene los campos nombre y descripción (que no pueden quedar vacíos) y un input para subir una imagen, que válida que la imagen efectivamente exista y sea en formato .jpeg o pn
![Captura de Pantalla 2022-05-16 a la(s) 17 11 13](https://user-images.githubusercontent.com/92653809/168675017-abd3580e-3ba8-4d5e-b91a-870967dcef88.png)
![Captura de Pantalla 2022-05-16 a la(s) 17 11 42](https://user-images.githubusercontent.com/92653809/168675024-03fd5ee0-a27f-4bab-a856-ef1c72ebd10e.png)
![Captura de Pantalla 2022-05-16 a la(s) 17 12 11](https://user-images.githubusercontent.com/92653809/168675033-740a9d20-4846-4e32-9d34-601572a3658f.png)
g

2022-05-16 23:41 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-16 23:42 UTC, FlaviaCohen requested changes

2022-05-16 23:42 UTC, FlaviaCohen commented on src/Components/Backoffice/Slides/SlidesForm.js
> +        if(input == initialValues.name && input.length < 4) {
Juli misma correccion que en el otro PR

2022-05-17 14:58 UTC, juliascode96 commented on src/Components/Backoffice/Slides/SlidesForm.js
> +        if(input == initialValues.name && input.length < 4) {
Corregido!

2022-05-17 15:38 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 03:07 UTC, FlaviaCohen approved these changes

2022-05-18 03:07 UTC, merged