FS02-25/feature - Get Method in privateApiService
alkemyTech/BBVA-React-T2 pull request #4
Opened 2022-05-10 14:45 UTC by iarabaya

Cree un metodo generico de axios que retorna tanto la respuesta como el error si ocurre en la llamada.
* Verifica si llega el parametro endpoint y sino tira error
* Sobre el id, tiene un valor por defecto pero no valida si el id existe efectivamente en base de datos por lo que solo lo concatena si es enviado como parametro

La verdad es que todavia esta incompleto porque hay cosas que no me cierran. 

Al menos hasta que las variables de entorno esten definidas deje el comentario con la BASE_URL, deberia removerlo pronto.
Por otro lado la constante config que incluye los headers estaba modificando lo que me traia la funcion Get, si la agregaba no me trae datos de ninguna de las rutas posibles, solo retornaba respuesta exitosa pero sin data. Por ende, por ahora esta fuera de axios.get 
Todavia no esta definida la funcion getAuthorization.

2022-05-10 16:11 UTC, FlaviaCohen requested changes

2022-05-10 16:11 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +export default Get;
Cambiaria este export a la linea 11 y lo dejaria solo como export, no default ya que tus compañeros también van a agregar servicios en este mismo archivo y no va a ser el único que se exporte desde acá

2022-05-10 16:25 UTC, iarabaya commented on src/Services/privateApiService.js
> +export default Get;
Listo, quedo como export { Get }
Gracias

2022-05-11 02:27 UTC, FlaviaCohen approved these changes

2022-05-11 02:27 UTC, merged