FS02-32/feature/componente SignUp
alkemyTech/BBVA-React-T2 pull request #44
Opened 2022-05-17 16:01 UTC by variniaquisbert

Acciones realizadas en esta rama:
- Creación del archivo _FormInput.js_ para armar la estructura de los inputs, los cuales recibiran por props su contenido y funcionalidad.
- Creación del archivo _FormInput.css_ para estilizar los inputs del formulario.
- Creación del archivo _SignUp.js_ para mostrar el logo, el formulario con sus respectivos campos (nombre, email, contraseña, confirmación de contraseña), botón para registrarse y en caso de tener en cuenta, puede acceder a ella haciendo click en "Ingresa!". Dentro del archivo, también se realizó un array de objetos que contienen los atributos de los inputs (name, type, placeholder, pattern, errorMessage).
- Creación del archivo _SignUp.css_ para estilizar todos los elementos que componen a _SignUp.js_
- Modificación del archivo _App.js_ para agregar las rutas de los componentes _Login_ y _SignUp_
- Modificación del archivo _general-styles.css_ para corregir una propiedad de una clase.

2022-05-17 16:08 UTC, variniaquisbert commented
Adjunto capturas del componente:
- Vista desde un navegador de escritorio:
![signUp-desktop](https://user-images.githubusercontent.com/105218447/168857773-25e52089-5644-41d1-9555-dcff2c1d9a3b.jpg)

- Vista desde un navegador de celular o tablet:
![signUp-phoneView](https://user-images.githubusercontent.com/105218447/168857792-497243d9-e5c0-4fca-bd92-8bf641acfdb4.jpg)

2022-05-17 16:26 UTC, FlaviaCohen requested changes

2022-05-17 16:26 UTC, FlaviaCohen commented on src/Components/Frontoffice/SignUp/FormInput.css
> +input {
Esto va a llevar a colision de estilos. En vez de referirte al elemento por su rol dale una clase. Lo mismo para todos los demas que no tengan clase

2022-05-17 16:26 UTC, FlaviaCohen commented on src/Components/Frontoffice/SignUp/SignUp.css
> +button {
Misma correccion

2022-05-17 16:26 UTC, FlaviaCohen commented on src/Components/Frontoffice/SignUp/SignUp.js
> +        e.preventDefault();
Aca falta el post al endpoint de /register con la informacion del formulario

2022-05-18 03:57 UTC, variniaquisbert commented on src/Components/Frontoffice/SignUp/SignUp.js
> +        e.preventDefault();
Ahí lo agregué 🙌

2022-05-18 03:57 UTC, variniaquisbert commented on src/Components/Frontoffice/SignUp/SignUp.css
> +button {
Corregido 👍

2022-05-18 03:57 UTC, variniaquisbert commented on src/Components/Frontoffice/SignUp/FormInput.css
> +input {
Corregido 👍

2022-05-18 14:00 UTC, FlaviaCohen requested changes

2022-05-18 14:00 UTC, FlaviaCohen commented on src/Components/Frontoffice/SignUp/SignUp.js
> +    const postUser = async () => {
En vez de declarar esto en una funcion aparte podes hacerlo todo dentro del handleSubmit. Cuando no vamos a utilizar esta logica en otro lado no tiene sentido declararla aparte.

2022-05-18 16:34 UTC, variniaquisbert commented on src/Components/Frontoffice/SignUp/SignUp.js
> +    const postUser = async () => {
Corregido!

2022-05-18 18:27 UTC, FlaviaCohen approved these changes

2022-05-18 18:27 UTC, merged