FS02-121/feature/restricción de la ruta /login
alkemyTech/BBVA-React-T2 pull request #46
Opened 2022-05-17 18:31 UTC by juliascode96

Llamada al método getToken desde el componente Login para checkear si el usuario ha iniciado sesión. Si se encuentra un token en el localStorage se hace una redirección al inicio

2022-05-17 22:47 UTC, juliascode96 commented
Agregué también un condicional al reader publico para ocultar los botones de registro e inicio de sesión cuando hay un token en el localStorage

2022-05-18 03:10 UTC, FlaviaCohen requested changes

2022-05-18 03:10 UTC, FlaviaCohen commented on src/Components/Frontoffice/PublicHeader/PublicHeader.js
> +let PublicHeader = () => {
Porque cambiaste const por let? Lo correcto seria const

2022-05-18 03:10 UTC, FlaviaCohen commented on src/Components/Frontoffice/PublicHeader/PublicHeader.js
> +           {getToken() ? (<></>) : (
Podrias declararlo asi: 

`{!getToken() && <div className="container-buttons-header">... }`

2022-05-18 18:54 UTC, FlaviaCohen approved these changes

2022-05-18 18:54 UTC, merged