Feature/fs02 54 Componente para renderizar seccion actividades
alkemyTech/BBVA-React-T2 pull request #49
Opened 2022-05-18 14:46 UTC by Gustavo27Gonzalez

![CapturaComponenteActividades](https://user-images.githubusercontent.com/74928839/169069775-b9e743f8-4713-4103-978a-6c78f48a91cb.PNG)
Ya está creado el componente e incorporado al app.js, el boton conocer mas redirige a una pagina de detalles que no esta creada y no se si la lleguemos a hacer

2022-05-18 18:33 UTC, FlaviaCohen approved these changes

2022-05-18 18:33 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 19:44 UTC, Gustavo27Gonzalez commented
Conflicto resuelto

2022-05-19 00:24 UTC, FlaviaCohen commented on src/Components/Frontoffice/ActivitiesFrontoffice/ActivitiesFrontofficeStyles.css
> +.activity-container-frontoffice{
Si este estilo esta en una carpeta que se llama /frontoffice no es necesario ponerle frontoffice al archivo. Nos queda un nombre re largo. 

Puede ser solamente /frontoffice/activitiesStyles.css 
Lo mismo con el js

2022-05-19 00:26 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +const Get = async (endpoint) => {
Estos cambios los podemos dejar porque estan bien, pero no son parte de esta tarea.

2022-05-19 00:33 UTC, FlaviaCohen requested changes

2022-05-19 00:33 UTC, FlaviaCohen commented on src/Components/Backoffice/News/News.js
> +import '../Activities/ActivitiesBackOffice.css';
Ahi vi que tambien tenias otra tarjeta con esta task. Se te mezclaron las branch.

2022-05-19 14:02 UTC, Gustavo27Gonzalez commented
![CapturaComponenteActividades](https://user-images.githubusercontent.com/74928839/169311990-812e86f8-4c8b-4410-9d10-0de835cb2618.PNG)
Tuve que meter mano en un par de cosas que no eran estrictamente de esta actividad porque se me habian mezclado las ramas y con los pr de ayer me habian ocupado el lugar del app.js donde llamaba al componente. En teoría está resuelto ya

2022-05-19 14:54 UTC, Gustavo27Gonzalez commented
A ver ahora? acepté los incoming change que me salian en el vscode

2022-05-19 15:30 UTC, FlaviaCohen requested changes

2022-05-19 16:17 UTC, closed without merging