Feature fs02 36-Formulario Activities Backoffice
alkemyTech/BBVA-React-T2 pull request #52
Opened 2022-05-18 17:44 UTC by BrianCiszewski-bbva

2022-05-18 18:40 UTC, FlaviaCohen requested changes

2022-05-18 18:40 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities/ActivitiesForm.css
> +body{
Este estilo es un estilo global. No creo que quieras que toda la aplicacion tenga fondo color azul pero si es asi deberia ir en la hoja de estilo global. Sino hay que darle una clase al div que quieras que tenga este estilo.

2022-05-18 18:40 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities/ActivitiesForm.js
> +    const fetch = async() =>{
fetch es una palabra reservada. Podrias llamar a este metodo `fetchData`

2022-05-18 18:40 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities/ActivitiesForm.js
> +        if(!id){
En vez de poner estos dos if podes hacer algo asi: 

```
if(id){
    logica de Put
}
else{
   logica de Post
}
```

2022-05-18 18:40 UTC, FlaviaCohen commented on src/Components/Backoffice/Activities/ActivitiesForm.js
> +            return;
Y este return solo no va, podrias retornar el alert

2022-05-18 18:40 UTC, FlaviaCohen commented on src/Services/Activities.Service.js
> +    activity['updated_at'] = getCurrentDate();
No es necesario mandarle el campo 'createdAt' o updatedAt, eso deberia setearlo automaticamente la api.

2022-05-18 18:41 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-18 19:25 UTC, BrianCiszewski-bbva commented
Listo!

2022-05-18 19:26 UTC, BrianCiszewski-bbva commented
Listo!

2022-05-19 00:37 UTC, FlaviaCohen requested changes

2022-05-19 00:37 UTC, FlaviaCohen commented on src/Services/Activities.Service.js
> +    return {...activityBasics, created_at: '', user_id: 0, updated_at: '', deleted_at: '', slug: ''};
No se los mandes vacios. Directamente no hay que mandarle los campos.

2022-05-19 02:12 UTC, BrianCiszewski-bbva commented on src/Services/Activities.Service.js
> +    return {...activityBasics, created_at: '', user_id: 0, updated_at: '', deleted_at: '', slug: ''};
oh, okey! entonces le paso los valores directo al post, ya q sino la funcion esa solo devolveria el parametro q recibe

2022-05-19 14:45 UTC, FlaviaCohen approved these changes

2022-05-19 15:34 UTC, FlaviaCohen commented on src/Services/Activities.Service.js
>  export async function updateActivity(id, updatedActivityFields){
No deberia ser necesaria. Lo unico que hay que mandarle es el body con los campos que son requeridos, tanto en el post como en el update. En el post ya quedo bien pero en el update no logro entender que esta haciendo.

2022-05-19 15:45 UTC, BrianCiszewski-bbva commented on src/Services/Activities.Service.js
>  export async function updateActivity(id, updatedActivityFields){
Se supone que trae la actividad de la api, y reemplaza los campos de esa actividad por los nuevos, pero ahora supongo q eso lo hace automatico el put?

Si al put le doy la url con el id, y en body solo los campos nuevos, lo actualiza solo? si es asi ya lo corrijo de esa forma

2022-05-19 15:51 UTC, FlaviaCohen commented on src/Services/Activities.Service.js
>  export async function updateActivity(id, updatedActivityFields){
Claro! El verbo PUT es para actualizar la informacion de una instancia de la base de datos. Siempre que hagas una peticion PUT va a reemplazar datos viejos por nuevos.

2022-05-19 15:58 UTC, FlaviaCohen approved these changes

2022-05-19 15:58 UTC, merged