Feature/fs02-118/proteccion rutas backoffice
alkemyTech/BBVA-React-T2 pull request #53
Opened 2022-05-18 18:12 UTC by fede16798

Funcionalidad para la protección de las rutas de backoffice diseñada. 

RoutesSecurity.js --> contiene toda la logica de la verificación de variable 'token' y 'isAdmin' en el localStorage. También se encarga de obtener el token para validar setar el valor de token y de isAdmin. (No actualiza el token en el caso de que venza, una vez seteado, ya lo toma como válido siempre).

backofficeLayout --> hace la lógica de la protección y redirección en cas de no se ser admin

2022-05-18 18:52 UTC, FlaviaCohen requested changes

2022-05-18 18:52 UTC, FlaviaCohen commented on src/Components/Backoffice/RoutesSecurity/RoutesSecurity.js
> +            if (isAdmin(res.data.data.user.role_id)){
Estas seguro que si no es admin el role_id es 0? 
Me parece que es 2 y en ese caso entraria al if en ambos casos.

2022-05-18 18:54 UTC, fede16798 commented on src/Components/Backoffice/RoutesSecurity/RoutesSecurity.js
> +            if (isAdmin(res.data.data.user.role_id)){
La respuesta de https://ongapi.alkemy.org/api/roles es: 
{
  "success": true,
  "data": [
    {
      "id": 1,
      "name": "Administrador",
      "description": "Admin",
      "created_at": null,
      "updated_at": "2021-08-03T23:31:55.000000Z",
      "deleted_at": null
    },
    {
      "id": 2,
      "name": "Standard",
      "description": "Standard User",
      "created_at": "2021-11-16T17:31:40.000000Z",
      "updated_at": "2021-11-16T17:31:40.000000Z",
      "deleted_at": null
    }
  ],
  "message": "Roles retrieved successfully"
}

2022-05-19 00:41 UTC, FlaviaCohen commented on src/Components/Backoffice/RoutesSecurity/RoutesSecurity.js
> +            if (isAdmin(res.data.data.user.role_id)){
Por eso... role 1 es administrador y role 2 es usuario regular o standard, como vos planteaste el condicional va a entrar en el if ya sea administrador o no. tendria que ser `if (isAdmin(res.data.data.user.role_id) == 1)`

2022-05-19 00:52 UTC, fede16798 commented on src/Components/Backoffice/RoutesSecurity/RoutesSecurity.js
> +            if (isAdmin(res.data.data.user.role_id)){
Claro, pasa que isAdmin es una funcion que devuelve true o false. Entonces la validación rol == 1 la hago en esa función

2022-05-19 15:56 UTC, FlaviaCohen commented on src/Components/Backoffice/RoutesSecurity/RoutesSecurity.js
> +            if (isAdmin(res.data.data.user.role_id)){
ahhhh... entonces estaria bien. No vi que hacias eso en isAdmin. Perfecto entonces

2022-05-19 15:56 UTC, FlaviaCohen commented
Solucionar conflictos

2022-05-19 16:51 UTC, FlaviaCohen requested changes

2022-05-19 16:51 UTC, FlaviaCohen commented on src/Services/privateApiService.js
> +<<<<<<< HEAD
Aca hay un conflicto sin resolver, y un console.log

2022-05-19 17:03 UTC, fede16798 commented on src/Services/privateApiService.js
> +<<<<<<< HEAD
Había hecho el save antes de de guardar. Pushear, perdon

2022-05-19 18:13 UTC, FlaviaCohen approved these changes

2022-05-19 18:13 UTC, merged