Feature fs02 117- logout
alkemyTech/BBVA-React-T2 pull request #64
Opened 2022-05-19 17:54 UTC by BrianCiszewski-bbva

2022-05-19 17:59 UTC, FlaviaCohen requested changes

2022-05-19 18:19 UTC, BrianCiszewski-bbva commented on src/Services/logout.js
> +    window.location.reload();
Lo habia hecho aparte por si lo agregabamos tmb en el header privado, pero ahi corrijo lo otro

2022-05-19 18:36 UTC, BrianCiszewski-bbva commented on src/Services/logout.js
> +    window.location.reload();
ahi probe con history, y funciona todo, menos el renderizado de los botones de sign out/login y que desaparezca el de sign out

2022-05-19 18:37 UTC, BrianCiszewski-bbva commented on src/Services/logout.js
> +    window.location.reload();
![image](https://user-images.githubusercontent.com/105220801/169375698-c05b5d47-f266-405a-9b98-80735575658b.png)

2022-05-19 23:54 UTC, FlaviaCohen commented on src/Services/logout.js
> +    window.location.reload();
Esta funcion ha yque borrarla porque ya no la estas usando

2022-05-20 02:11 UTC, FlaviaCohen approved these changes

2022-05-20 02:11 UTC, merged