armado de login version mobile y desktop
alkemyTech/BBVA-React-T2 pull request #8
Opened 2022-05-10 20:07 UTC by Gustavo27Gonzalez

Creación de componente Login con distinta disposición de los elementos en tamaño mobile y desktop

2022-05-11 02:48 UTC, FlaviaCohen commented
Cambié el nombre del PR, recorda que siempre debe ser Id de tarjeta + feature o fix segun corresponda + breve descripcion

2022-05-11 02:48 UTC, FlaviaCohen commented
Recorda poner capturas de pantalla sobre el trabajo que hiciste en la descripcion del PR, sobretodo cuando hay elementos visuales

2022-05-11 02:48 UTC, FlaviaCohen commented
Recorda hacer commits atomicos y no solo uno al final del trabajo

2022-05-11 02:54 UTC, FlaviaCohen requested changes

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +    console.log('Envío de formulario: ' , email, password)
No se dejan console.logs en los PRs.

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +const [formData, setFormData] = useState({email: '', password:''})
Estas declarando este estado pero no lo estas utilizando. En cada input debe haber un atributo onChange que ejecute una funcion handleChange y setee los valores del input como estado local. Luego ese estado local se pasa como value en cada input. De esa manera controlamos el formulario. 

Si tenes dudas sobre esto hablá con Jenko del team 1 que estuvo trabajando en eso.

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +    e.preventDefault()
Falta la logica para enviar la informacion a la api. Consulta el swagger, la seccion del endpoint Auth ya que habria que hacer un post a /login

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/LoginStyle.css
> +  background-image: url(./imagenONG.jpeg);
es posible que te falten comillas en este path?

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/LoginStyle.css
> +@media (max-width: 768px) {
La forma correcta de declarar medias queries es dentro de la clase que lo requiera y no al reves. De esta forma evitamos que una misma clase tenga su estilo disperso en varios lugares y el codigo es mas facil de mantener si el proyecto crece mucho.

2022-05-11 02:54 UTC, FlaviaCohen commented on src/Components/Login/LoginStyle.css
> +@media (min-width: 768px) {
Mismo comentario

2022-05-12 01:55 UTC, FlaviaCohen requested changes

2022-05-12 01:55 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +            onSubmit={(user, { resetForm }) => {
Mismo comentario que en validate

2022-05-12 01:55 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +            validate={(user) => {
Esta logica hay que declararla en una funcion antes del return y aca solo pasarsela al on submit. No es buena practica incluir logica dentro del jsx

2022-05-12 16:53 UTC, Gustavo27Gonzalez commented
![CapturaHandleSubmitFueraDelJSX](https://user-images.githubusercontent.com/74928839/168127908-a30c9cd5-c1e7-4e61-86ff-1434d3ca10cb.PNG)
![CapturaValidateDentroJSX](https://user-images.githubusercontent.com/74928839/168127915-d41b4267-2a96-4ec4-8967-3dac6e59553e.PNG)
Lógica del handleSubmit movida fuera del jsx. La lógica del validate no pude sacarla fuera del jsx siguiendo la documentación de formik porque deja de funcionar.

2022-05-12 23:50 UTC, FlaviaCohen requested changes

2022-05-12 23:50 UTC, FlaviaCohen commented on src/Components/Login/Login.js
> +    console.log(user)
No dejemos console.logs en los PRs

2022-05-12 23:50 UTC, FlaviaCohen commented on src/Services/Login.service.js
> +  return axios.post("https://ongapi.alkemy.org/api/login", body);
Podes usarl as variables de entorno

2022-05-13 16:52 UTC, Gustavo27Gonzalez commented
'saque console.log, utilizacion de variable de entorno en llamada axios

2022-05-14 14:38 UTC, FlaviaCohen approved these changes

2022-05-14 14:39 UTC, merged